sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "9"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - node_js: "8"
      env: TEST_SUITE=lint
script: npm run-script $TEST_SUITE
